### ISSUE TITLE
requests never end when a connection fails

### ISSUE THREAD

**Issue by gshively11** [godaddy/mssql-pool-party#8] opened 2019-02-25 20:24 UTC
`mssql-pool-party` uses `node-mssql` internally. `node-mssql` uses `generic-pool` for connection pool management. However, it's being used improperly, resulting in an infinite loop when a connection fails. This started in `node-mssql@4.x.x`, so `mssql-pool-party` is impacted starting at `0.3.0` onward.

https://github.com/tediousjs/node-mssql/issues/805
https://github.com/tediousjs/node-mssql/issues/470
https://github.com/tediousjs/node-mssql/pull/808

We recommend to avoid `mssql-pool-party@0.3.x` for now if you can. A fix will hopefully arrive soon.

**Comment by dhensby** [comment] 2019-02-26 11:45
Hopefully some semblance of a fix will be in https://github.com/tediousjs/node-mssql/pull/806

I'm not sure the problem is that `generic-pool` is being used "improperly", from what I can tell `generic-pool` is "broken" and it's feature set / behaviour is incompatible with managing a set of resources that may rely on an unavailable service.

see:

https://github.com/coopernurse/node-pool/issues/256
https://github.com/coopernurse/node-pool/issues/175

**Comment by gshively11** [comment] 2019-02-26 16:04
Sorry @dhensby, didn't mean to sound accusatory. During my investigation yesterday I thought I read in their docs somewhere that `generic-pool` would continue trying to create a resource if it encountered a failure, but I don't see that anywhere now, so my mistake. I agree that it does seem broken, or at least undocumented.

**Comment by dhensby** [comment] 2019-02-26 16:15
No problem, I think it needs clarity where the issue is coming from.

It is currently intended in `generic-pool` (though not sure about the docs) that it will immediately retry resource creation on failure, but that doesn't make sense in a DB pool scenario.

**Comment by dhensby** [comment] 2019-03-08 15:22
v5 should have mitigated this issue and v6 removed it (as we've dropped `generic-pool`)

**Closed as completed** 2019-11-04 16:32 UTC
Labels: bug
